services:
  - name: ip-locator-backend
    type: web
    env: node
    region: oregon  # or other Render regions, like 'singapore', 'frankfurt', etc.
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: MONGODB_URI
        value: <your-mongodb-connection-string>
